#el puerto de arranque para el servidor tomcat se coje del servidor de configuracion
#server:
#  port: 8898
spring:
  application:
    name: restfulapp
  profiles:
    active: dev
  config:
    import: 
      - optional:configserver:http://192.168.1.126:9001
  cloud:
    config:
      uri: http://192.168.1.126:9001 
      failFast: true
